-- AlterTable
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "series" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "QuizAttempt" ADD COLUMN IF NOT EXISTS "series" INTEGER;
ALTER TABLE "QuizAttempt" ADD COLUMN IF NOT EXISTS "isMockExam" BOOLEAN NOT NULL DEFAULT false;
